# Generated by Django 5.2.15 on 2026-06-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_availability_project_business_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
