# Generated by Django 5.2.15 on 2026-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
