# Generated by Django 5.2.15 on 2026-06-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('artifacts', '0002_extend_project_artifact'),
        ('knowledge', '0001_initial'),
        ('projects', '0003_project_repository_data'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='analysis_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='analysis.analysisjob'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='discovered_by',
            field=models.CharField(blank=True, choices=[('REPOSITORY_SCANNER', 'Repository Scanner'), ('TECH_DISCOVERY', 'Technology Discovery'), ('TREE_SITTER', 'Tree-sitter Analyzer'), ('LSP_ANALYZER', 'LSP Analyzer'), ('AI_ANALYZER', 'AI Analyzer'), ('USER_INPUT', 'User Input')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgerelationship',
            name='analysis_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_relationships', to='analysis.analysisjob'),
        ),
        migrations.AddField(
            model_name='knowledgerelationship',
            name='discovered_by',
            field=models.CharField(blank=True, choices=[('REPOSITORY_SCANNER', 'Repository Scanner'), ('TECH_DISCOVERY', 'Technology Discovery'), ('TREE_SITTER', 'Tree-sitter Analyzer'), ('LSP_ANALYZER', 'LSP Analyzer'), ('AI_ANALYZER', 'AI Analyzer'), ('USER_INPUT', 'User Input')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgerelationship',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='item_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgerelationship',
            name='relationship_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['repository', 'item_type'], name='knowledge_k_reposit_10fc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['repository', 'analysis_job'], name='knowledge_k_reposit_dc8b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['analysis_job'], name='knowledge_k_analysi_81f24a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelationship',
            index=models.Index(fields=['relationship_type'], name='knowledge_k_relatio_6d65b1_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelationship',
            index=models.Index(fields=['discovered_by'], name='knowledge_k_discove_3b8c14_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelationship',
            index=models.Index(fields=['analysis_job'], name='knowledge_k_analysi_f42bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelationship',
            index=models.Index(fields=['source_item', 'relationship_type'], name='knowledge_k_source__84b9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelationship',
            index=models.Index(fields=['target_item', 'relationship_type'], name='knowledge_k_target__509e46_idx'),
        ),
    ]
