# Generated by Django 5.2.15 on 2026-06-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgeitem_analysis_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeitem',
            name='discovered_by',
            field=models.CharField(blank=True, choices=[('REPOSITORY_SCANNER', 'Repository Scanner'), ('TECH_DISCOVERY', 'Technology Discovery'), ('TREE_SITTER', 'Tree-sitter Analyzer'), ('LSP_ANALYZER', 'LSP Analyzer'), ('AI_ANALYZER', 'AI Analyzer'), ('USER_INPUT', 'User Input'), ('REPOSITORY_CLASSIFIER', 'Repository Classifier')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgerelationship',
            name='discovered_by',
            field=models.CharField(blank=True, choices=[('REPOSITORY_SCANNER', 'Repository Scanner'), ('TECH_DISCOVERY', 'Technology Discovery'), ('TREE_SITTER', 'Tree-sitter Analyzer'), ('LSP_ANALYZER', 'LSP Analyzer'), ('AI_ANALYZER', 'AI Analyzer'), ('USER_INPUT', 'User Input'), ('REPOSITORY_CLASSIFIER', 'Repository Classifier')], db_index=True, max_length=50),
        ),
    ]
