# Generated by Django 5.2.15 on 2026-06-20 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_availability_project_business_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project')),
            ],
        ),
    ]
