# Generated by Django 5.2.15 on 2026-06-20 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_availability_project_business_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(max_length=100)),
                ('bucket_name', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('upload_status', models.CharField(default='completed', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.project')),
            ],
        ),
    ]
