# Generated by hand to extend ProjectArtifact and migrate existing data.

from django.db import migrations, models
import django.db.models.deletion

def migrate_artifact_types(apps, schema_editor):
    ProjectArtifact = apps.get_model('artifacts', 'ProjectArtifact')
    # Update Business
    ProjectArtifact.objects.filter(artifact_type='Business').update(artifact_type='business_document')
    # Update Compliance
    ProjectArtifact.objects.filter(artifact_type='Compliance').update(artifact_type='compliance_document')
    # Update Architecture
    ProjectArtifact.objects.filter(artifact_type='Architecture').update(artifact_type='architecture_document')
    # Update Infrastructure
    ProjectArtifact.objects.filter(artifact_type='Infrastructure').update(artifact_type='iac_artifact')

def reverse_artifact_types(apps, schema_editor):
    ProjectArtifact = apps.get_model('artifacts', 'ProjectArtifact')
    ProjectArtifact.objects.filter(artifact_type='business_document').update(artifact_type='Business')
    ProjectArtifact.objects.filter(artifact_type='compliance_document').update(artifact_type='Compliance')
    ProjectArtifact.objects.filter(artifact_type='architecture_document').update(artifact_type='Architecture')
    ProjectArtifact.objects.filter(artifact_type='iac_artifact').update(artifact_type='Infrastructure')
    ProjectArtifact.objects.filter(artifact_type='kubernetes_artifact').update(artifact_type='Infrastructure')
    ProjectArtifact.objects.filter(artifact_type='container_artifact').update(artifact_type='Infrastructure')

class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        # Rename name to file_name
        migrations.RenameField(
            model_name='projectartifact',
            old_name='name',
            new_name='file_name',
        ),
        # Rename size to file_size
        migrations.RenameField(
            model_name='projectartifact',
            old_name='size',
            new_name='file_size',
        ),
        # Add uploaded_by
        migrations.AddField(
            model_name='projectartifact',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_artifacts', to='authentication.user'),
        ),
        # Alter artifact_type choices
        migrations.AlterField(
            model_name='projectartifact',
            name='artifact_type',
            field=models.CharField(choices=[('business_document', 'Business Document'), ('compliance_document', 'Compliance & Security Document'), ('architecture_document', 'Architecture Decisions Document'), ('iac_artifact', 'IaC Artifact'), ('kubernetes_artifact', 'Kubernetes Configuration'), ('container_artifact', 'Containerization Configuration')], max_length=100),
        ),
        # Run python code to migrate existing data
        migrations.RunPython(migrate_artifact_types, reverse_code=reverse_artifact_types),
    ]
